spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_security
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org:
      springframework:
        web: DEBUG  # Set logging level for Spring Web to DEBUG

